-- MySQL Script generated by MySQL Workbench
-- lun 25 ene 2021 15:23:04 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bolsa-de-la-compra
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bolsa-de-la-compra` ;

-- -----------------------------------------------------
-- Schema bolsa-de-la-compra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bolsa-de-la-compra` ;
USE `bolsa-de-la-compra` ;

-- -----------------------------------------------------
-- Table `bolsa-de-la-compra`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bolsa-de-la-compra`.`groups` ;

CREATE TABLE IF NOT EXISTS `bolsa-de-la-compra`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsa-de-la-compra`.`list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bolsa-de-la-compra`.`list` ;

CREATE TABLE IF NOT EXISTS `bolsa-de-la-compra`.`list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_group` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_list_1_idx` (`id_group` ASC) VISIBLE,
  CONSTRAINT `fk_list_1`
    FOREIGN KEY (`id_group`)
    REFERENCES `bolsa-de-la-compra`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsa-de-la-compra`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bolsa-de-la-compra`.`products` ;

CREATE TABLE IF NOT EXISTS `bolsa-de-la-compra`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsa-de-la-compra`.`groups_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bolsa-de-la-compra`.`groups_users` ;

CREATE TABLE IF NOT EXISTS `bolsa-de-la-compra`.`groups_users` (
  `id_group` INT UNSIGNED NOT NULL,
  `id_user` INT UNSIGNED NOT NULL,
  INDEX `fk_groups_users_1_idx` (`id_group` ASC) VISIBLE,
  CONSTRAINT `fk_groups_users_1`
    FOREIGN KEY (`id_group`)
    REFERENCES `bolsa-de-la-compra`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolsa-de-la-compra`.`list_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bolsa-de-la-compra`.`list_products` ;

CREATE TABLE IF NOT EXISTS `bolsa-de-la-compra`.`list_products` (
  `id_list` INT UNSIGNED NOT NULL,
  `id_products` INT UNSIGNED NOT NULL,
  `units` FLOAT UNSIGNED NOT NULL,
  `price` FLOAT NULL,
  `date` DATE NOT NULL,
  INDEX `products_idx` (`id_products` ASC) VISIBLE,
  INDEX `list_idx` (`id_list` ASC) VISIBLE,
  CONSTRAINT `products`
    FOREIGN KEY (`id_products`)
    REFERENCES `bolsa-de-la-compra`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `list`
    FOREIGN KEY (`id_list`)
    REFERENCES `bolsa-de-la-compra`.`list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
